// qqlogin_nt_ldm 域 — 5 消息（自动还原自 QQ 9.3.55 jadx 反编译源码）
// tag = (field_number << 3) | wire_type；0=varint 1=fixed64 2=len 5=fixed32
// 注：跨域/歧义的嵌套消息引用降级为 bytes，原始类型名保留在行尾注释中
syntax = "proto3";
package qq.qqlogin_nt_ldm;

// ==== source: qqlogin/nt_ldm/NTLoginDeviceManager$AutoLoginSwitch.java ====
message AutoLoginSwitch {
  LoginApp login_app = 1;
  uint32 encrypt_guid_version = 2;
  uint32 auto_login = 3;
  uint32 trusted_device = 4;
}

// ==== source: qqlogin/nt_ldm/NTLoginDeviceManager$GetAutoLoginSwitchesReq.java ====
message GetAutoLoginSwitchesReq {
  repeated AutoLoginSwitch auto_login_switches = 1;
}

// ==== source: qqlogin/nt_ldm/NTLoginDeviceManager$GetAutoLoginSwitchesRsp.java ====
message GetAutoLoginSwitchesRsp {
  repeated AutoLoginSwitch auto_login_switches = 1;
}

// ==== source: qqlogin/nt_ldm/NTLoginDeviceManager$LoginApp.java ====
message LoginApp {
  bytes guid = 1;
  uint32 app_id = 2;
  string app_name = 3;
}

// ==== source: qqlogin/nt_ldm/NTLoginDeviceManager$UpdateAutoLoginSwitchReq.java ====
message UpdateAutoLoginSwitchReq {
  AutoLoginSwitch auto_login_switch = 1;
}
