// qqlogin_qrlogin 域 — 4 消息（自动还原自 QQ 9.3.55 jadx 反编译源码）
// tag = (field_number << 3) | wire_type；0=varint 1=fixed64 2=len 5=fixed32
// 注：跨域/歧义的嵌套消息引用降级为 bytes，原始类型名保留在行尾注释中
syntax = "proto3";
package qq.qqlogin_qrlogin;

// ==== source: qqlogin/qrlogin/extinfo/QrLoginExtInfo$DevInfo.java ====
message DevInfo {
  bytes dev_type = 1;
  bytes dev_name = 2;
}

// ==== source: qqlogin/qrlogin/extinfo/QrLoginExtInfo$GenInfo.java ====
message GenInfo {
  uint32 client_type = 1;
  uint32 client_ver = 2;
  uint32 client_appid = 3;
}

// ==== source: qqlogin/qrlogin/extinfo/QrLoginExtInfo$QrExtInfo.java ====
message QrExtInfo {
  DevInfo dev_info = 1;
  string qr_url = 2;
  string qr_sig = 3;
  GenInfo gen_info = 4;
}

// ==== source: qqlogin/qrlogin/extinfo/QrLoginExtInfo$ScanExtInfo.java ====
message ScanExtInfo {
  bytes guid = 1;
  bytes imei = 2;
  int32 scan_scene = 3;
  bool allow_auto_renew_ticket = 4;
  bool invalid_gen_ticket = 5;
}
